### PR TITLE
Server integration

### PR DESCRIPTION
**Pull request by paul-codes-1**

### CODE REVIEW

**Comment by travisoneill** [comment]
Added some docs updates and got rid of some deprecated stuff a few hours ago.  Merge in if you can. If not, it's all stuff that could be easily done in another PR, so not worth the effort to reconcile.

**Comment by paul-codes-1** [comment]
Looks like somewhere in these changes we overrode the logging of the start actions for creating files and directories. When I run `eos start` I'm not getting `created xxx` logged; it's only messages from the server creation. Gonna look into it. Closing this PR for now.

**Comment by paul-codes-1** [comment]
Good to go. Print statements in `eos start` roll by sexily.

**Comment by travisoneill** [comment]
Looks good to me.  Let's get it merged, and I can add in some more frameworks.

**Comment by alexmattson** [comment]
What is the command now to run the server?

**Comment by paul-codes-1** [comment]
`eos server` to run the server. Slack me if you hit an issue. I'm online and working on DB stuff.

**Comment by alexmattson** [comment]
That doesn't seem to work, and there's a comment in the cli file stating its deprecated. I think that the server generation is deprecated but the the cli should not be as that is the command used to run the server.

**Comment by paul-codes-1** [comment]
Oh yeah, the eos server command is not deprecated. That comment was added by mistake. Slack me real quick so we can chat for a sec.

**Pull request merged**
